---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      ansible.builtin.wait_for_connection:

    - name: "install python for Ansible."
      raw: bash -c "test -e /usr/bin/python3 || (apt -qqy update && apt install -qqy python python-pip python3 python3-pip)"


  # Get the environment variables from CircleCI and add to the EC2 instance
 
  roles:
    - configure-server