- name: "Create directory"
  file:
    path: /home/ubuntu/udapeople
    state: directory

- name: unzip files
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/udapeople/

- name: Update repositories cache
  apt:
    update_cache: yes

- name: "Install NodeJS"
  become: true
  apt:
    name: "nodejs"
    state: latest
    update_cache: yes

- name: "Install NPM"
  become: true
  apt:
    name: "npm"
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes

- name: "Start Application"
  become: yes
  shell: |
    cd /home/ubuntu/udapeople/
    npm install
    pm2 stop default
    pm2 start npm -- start