- name: "Create directory"
  file:
    path: /home/ubuntu/udapeople
    state: directory
- name: unzip files
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/udapeople/
- name: "Start Application"
  become: yes
  shell: |
    cd /home/ubuntu/udapeople/
    sudo apt update
    sudo apt install npm  
    npm install
    pm2 stop default
    pm2 start npm -- start